### ISSUE TITLE
Issues with Jetpack's WP.com API interface

### ISSUE THREAD

**Issue by kraftbj** [rlankhorst/really-simple-ssl#57] opened 2017-06-09 02:18 UTC
Howdy!

A couple of things. 
Regarding https://github.com/rlankhorst/really-simple-ssl/blob/ef060ec8dcff4d3020cfeeaa5b011011cf193758/class-admin.php#L685 , this should no longer be necessary as JP now checks for 80, 443, or the constant-defined port via https://github.com/Automattic/jetpack/blob/master/class.jetpack-signature.php#L50

In Jetpack support, we've seen an uptick of issues where a mutual customer is using Really Simple SSL and Jetpack when attempting to manage their site via WordPress.com (which utilizes XMLRPC communication with the site) resulting in Jetpack's signature verification failure.

I haven't been able to recreate or duplicate the problem in a test environment yet, so I'm hoping you may have some ideas.

The specific thing so far is disabling the mixed content fixer in this plugin appears to resolve the issue.

I'm not sure exactly how this plugin enables SSL and would love your input. My hypothesis at the moment is the mixed content fixer is modifying the Jetpack signature that is created via https://github.com/Automattic/jetpack/blob/master/class.jetpack-signature.php#L24-L212 _some_ of the time. Our typical debug tools don't indicate a problem, which suggests to me that the signature process is working the majority of the time, but there are some requests that cause it to fail.

On my end, I'm going to keep trying to create a test environment that fails, but any insight or ideas you have in the mean time would be greatly appreciated!

**Comment by rlankhorst** [comment] 2017-06-09 07:02
Hi, thanks for reporting this. As it seems to be caused by the mixed content fixer, I'll focus on that. It's basically simple: it uses output buffering to retrieve the html for the page that is being generated, and replaces all:
- instances of the home_url, both www and non www and escaped
- all src="http:// and srcset="http://
- url(http, <link href="http, <meta property, <form action="http. 

Then it inserts a data-rsssl=1 marker in the body tag so it can be verified it is working. 

As this happens consistently, it wouldn't know why it doesn't consistently cause an issue. 

Possibly checking a function like is_jetpack_signature() that could tell the plugin if it should apply the mixed content fixer would be a solution.

**Comment by kraftbj** [comment] 2017-06-12 15:42
Does the mixed content fixer also apply to output from the WP Rest API or via XMLRPC requests?

**Comment by rlankhorst** [comment] 2017-06-12 16:56
It hooks in on 'init', until 'shutdown', so I expect it to apply on all output. I have added a condition to prevent the mixed content fixer from activating on wp_rest_api requests in the 2.5.18 branche. Maybe that fixes the issue?

**Comment by kraftbj** [comment] 2017-06-12 21:52
You can check for an XMLRPC request via PHP constant
` if ( defined( 'XMLRPC_REQUEST' ) && XMLRPC_REQUEST ) {`

We're still getting reports, but I can't figure out how to duplicate it. If you're willing to ship that, I can let you know if it seems to solve the Jetpack issue or if we can find another way to get it into folks hands for testing.

Cheers!

**Comment by rlankhorst** [comment] 2017-06-13 07:29
I have merged that into the master here on Github. I would prefer to ask users to try this version if they run into any issues with JetPack. If that solves it for them, and it runs without issues on my testsites, I'll add it to the next update, which should be in about 4 weeks. 

If users submit a support request about this with me, I will do the same. That should tell us if this solves the issue.

**Comment by kraftbj** [comment] 2017-06-20 17:02
So far so good with this. Not a large sample size, but will let you know if anything is amiss.

**Comment by rlankhorst** [comment] 2017-06-20 20:56
That's good to hear :) I've also moved the hook the front-end mixed content fixer is activating on to the template_redirect. As this hook only fires on an actual page load this should prevent any issues like this I think.

**Comment by rlankhorst** [comment] 2017-06-23 13:34
will publish the current master as 2.5.18 in a couple of days, with proposed changes that I expect to fix this issue.

**Comment by rlankhorst** [comment] 2017-06-27 15:01
I'll close this issue for now, I think the current update will have fixed it, but let me know if you get any reports from users!

**Closed** 2017-06-27 15:01 UTC

**Comment by kraftbj** [comment] 2017-06-28 20:43
Still all quiet! Again, I appreciate the help!
